### ISSUE TITLE
editChannel call seems to be dropped

### ISSUE THREAD

**Issue by MichaelTheriot** [abalabahaha/eris#263] opened 2017-07-14 21:16 UTC
I'm trying to create a new voice channel with predefined user limit and role permissions.

```js
const Eris = require('eris');
const bot = new Eris(token);

bot.on('shardReady', async function () {
  const guild = bot.guilds.get(guildID);
  const channel = await guild.createChannel('test', 2);

  while (!guild.channels.has(channel.id)) { // temp bug fix
    await new Promise(resolve => setTimeout(resolve, 1000));
  }

  try {
    await Promise.all([
      channel.edit({userLimit: 1}),
      channel.editPermission(roleID, 0, 1048576, 'role')
    ]);
  } catch (err) {
    console.error(err);
  }

  console.log(channel.userLimit);
});

bot.connect();
```

Several runs:
```
0
0
0
0
```

The permissions update correctly but user limit updates only half of the time. When it does update correctly the output is still 0 as well. No errors thrown in either scenario.

**Comment by abalabahaha** [comment] 2017-07-14 21:29
`channel.userLimit` won't change immediately because of what I described in #262 (cache updated by gateway WebSocket). What do the audit logs say about the user limit?

Also in the future please ask questions in [#js_eris in Discord API](https://discord.gg/discord-api) and not as GitHub tickets

**Comment by MichaelTheriot** [comment] 2017-07-14 21:32
I don't think the audit log records user limit updates. I've never seen one made by the bot or myself. Channel overrides show up correctly.

I didn't add the question label. I assume this is an error since the update does not occur and no error is thrown by the library.

**Comment by abalabahaha** [comment] 2017-07-17 03:41
This seems to be fixed in dev, since I was unable to reproduce this after creating and editing 100 channels. Release will be landing sometime in the next week.

**Closed as completed by abalabahaha** 2017-07-17 03:41 UTC
Labels: bug
