### ISSUE TITLE
1006 error loop

### ISSUE THREAD

**Issue by WoodManGitHub** [abalabahaha/eris#931] opened 2020-05-03 14:13 UTC
I try to write a very simple code as following:
https://gist.github.com/WoodManGitHub/f3e1ee3fd296296f81fac01e5d100047

After running this code for a moment, I encountered 1006 error:
https://gist.github.com/WoodManGitHub/cfca36f901ee7cdf9bfeb1a796e3d6cd

And it started to loop until I restart the bot

**Comment by abalabahaha** [comment] 2020-05-03 22:15
This is likely a duplicate of #921

**Closed as completed by abalabahaha** 2020-05-03 22:15 UTC
Labels: bug, duplicate
