### ISSUE TITLE
Undefined 'id' in Shard.js

### ISSUE THREAD

**Issue by Coolguy3289** [abalabahaha/eris#966] opened 2020-06-13 08:06 UTC
Running eris 0.13.1, randomly get the following stack trace on either shard (0 or 1 or both):
```0|TrelloBot  |  06/13 08:04:42   error    Error in shard 0
0|TrelloBot  |  TypeError: Cannot set property 'id' of undefined
0|TrelloBot  |     at Shard.wsEvent (/home/trello/TrelloBot/node_modules/eris/lib/gateway/Shard.js:592:48)
0|TrelloBot  |     at Shard.onWSMessage (/home/trello/TrelloBot/node_modules/eris/lib/gateway/Shard.js:1904:26)
0|TrelloBot  |     at WebSocket.ws.onmessage (/home/trello/TrelloBot/node_modules/eris/lib/gateway/Shard.js:1795:33)
0|TrelloBot  |     at WebSocket.onMessage (/home/trello/TrelloBot/node_modules/ws/lib/event-target.js:125:16)
0|TrelloBot  |     at WebSocket.emit (events.js:315:20)
0|TrelloBot  |     at Receiver.receiverOnMessage (/home/trello/TrelloBot/node_modules/ws/lib/websocket.js:800:20)
0|TrelloBot  |     at Receiver.emit (events.js:315:20)
0|TrelloBot  |     at Receiver.dataMessage (/home/trello/TrelloBot/node_modules/ws/lib/receiver.js:436:14)
0|TrelloBot  |     at Receiver.getData (/home/trello/TrelloBot/node_modules/ws/lib/receiver.js:366:17)
0|TrelloBot  |     at Receiver.startLoop (/home/trello/TrelloBot/node_modules/ws/lib/receiver.js:142:22)
0|TrelloBot  |     at Receiver._write (/home/trello/TrelloBot/node_modules/ws/lib/receiver.js:77:10)
0|TrelloBot  |     at doWrite (_stream_writable.js:403:12)
0|TrelloBot  |     at writeOrBuffer (_stream_writable.js:387:5)
0|TrelloBot  |     at Receiver.Writable.write (_stream_writable.js:318:11)
0|TrelloBot  |     at TLSSocket.socketOnData (/home/trello/TrelloBot/node_modules/ws/lib/websocket.js:875:35)
0|TrelloBot  |     at TLSSocket.emit (events.js:315:20)
0|TrelloBot  |     at addChunk (_stream_readable.js:295:12)
0|TrelloBot  |     at readableAddChunk (_stream_readable.js:271:9)
0|TrelloBot  |     at TLSSocket.Readable.push (_stream_readable.js:212:10)
0|TrelloBot  |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

```

**Comment by bsian03** [comment] 2020-06-13 10:12
Fixed in #952 and dupe of #951

**Comment by Coolguy3289** [comment] 2020-06-13 18:06
Awesome. @abalabahaha Any ETA on when this will be put into a release?

**Comment by bsian03** [comment] 2020-06-13 21:47
Whenever he can be bothered

**Comment by abalabahaha** [comment] 2020-06-14 15:50
Probably today or tomorrow, need to wrap up some testing.

> Whenever he can be bothered

Thanks very helpful /s

**Closed as completed** 2020-06-14 15:50 UTC
Labels: bug, duplicate

**Comment by Coolguy3289** [comment] 2020-06-14 16:47
Appreciate it!

**Comment by bsian03** [comment] 2020-06-14 20:13
> Thanks very helpful /s

Oh that's how I roll
