### ISSUE TITLE
Discord is removing support for discordapp.com.

### ISSUE THREAD

**Issue by Eegras** [abalabahaha/eris#982] opened 2020-07-17 09:35 UTC
I got this message from Discord staff themselves.

> Discord API Domain Migration
>
> Last month, we excitedly announced our official move to discord.com. It was a long time in the making, and the work isn't done yet! For now, our API will continue to handle requests made to discordapp.com. On November 7, 2020 we will be dropping support for the discordapp.com domain in favor of discord.com. Please ensure that your libraries, bots, and applications are updated accordingly.
>
> Due to technical constraints, our CDN domain will not be migrated and will remain cdn.discordapp.com for the foreseeable future.

**Comment by abalabahaha** [comment] 2020-07-17 10:59
Duplicate of #932 #939. This change was announced over 2 months ago in DAPI and DDevs.

**Closed as completed by abalabahaha** 2020-07-17 10:59 UTC
Labels: duplicate, Discord
