### ISSUE TITLE
this.receiveStreamOpus.destroy is not a function

### ISSUE THREAD

**Issue by Yahweasel** [abalabahaha/eris#366] opened 2018-02-27 15:32 UTC
I was getting the following error occasionally:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: this.receiveStreamOpus.destroy is not a function
    at VoiceConnection._destroy (/home/yahweasel/craig/node_modules/eris/lib/voice/VoiceConnection.js:170:36)
    at Map.leave (/home/yahweasel/craig/node_modules/eris/lib/voice/VoiceConnectionManager.js:113:20)
    at Shard.wsEvent (/home/yahweasel/craig/node_modules/eris/lib/gateway/Shard.js:722:54)
    at Shard.onWSMessage (/home/yahweasel/craig/node_modules/eris/lib/gateway/Shard.js:1716:26)
    at ws.onmessage (/home/yahweasel/craig/node_modules/eris/lib/gateway/Shard.js:1591:33)
    at WebSocketClient.internalOnMessage (/home/yahweasel/craig/node_modules/uws/uws.js:103:17)
    at native.client.group.onMessage (/home/yahweasel/craig/node_modules/uws/uws.js:57:15)
```

I added a check to it in eris/lib/voice/VoiceConnection.js:

```javascript
        if(this.receiveStreamOpus) {
            if (typeof this.receiveStreamOpus.destroy === "function") {
                this.receiveStreamOpus.destroy();
            } else {
                console.error("vvvvv WONKY RECEIVESTREAMOPUS vvvvv\n", this.receiveStreamOpus, "\n^^^^^");
            }
        }
```

Getting output like so:

```
vvvvv WONKY RECEIVESTREAMOPUS vvvvv
 VoiceDataStream {
  domain: null,
  _events: { opus: [Function: onReceive], data: [Function] },
  _eventsCount: 2,
  _maxListeners: undefined,
  type: 'opus' } 
^^^^^
```

Two notes: (1) I have workarounds in place for #359, so it's entirely possible that this is being caused by such a workaround, (2) I always use opusOnly: true.

This workaround for this behavior seems to be harmless, and I'm not getting any crashes or other such strangeness with it in place. If there's some other info you'd like me to output for comparison, I can.

**Comment by Yahweasel** [comment] 2018-02-27 15:33
(Oh, and it's worth mentioning that the irrelevant "opus" event there is due to transitioning from discord.js to Eris. As far as I'm aware, having events that will never fire should be harmless, so I certainly hope that's not the issue :) )

**Comment by abalabahaha** [comment] 2018-02-27 19:23
Duplicate of #359, which happens to be the issue you opened. Error stack is similar to the one in my comment there, caused by the same bug. Fix is in dev branch if you'd like to test.

**Closed as completed by abalabahaha** 2018-02-27 19:23 UTC
Labels: bug, duplicate, voice
