### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ProfessorVarox** [abalabahaha/eris#1230] opened 2021-06-29 19:05 UTC
Everytime I send an interaction response (I'm using axios as Eris dosn't support Interactions atm) I get this error:

```
TypeError: Cannot read property 'map' of undefined
    at Message.update (D:\Discord_Bots\reportsystem\node_modules\eris\lib\structures\Message.js:249:43)
    at Map.update (D:\Discord_Bots\reportsystem\node_modules\eris\lib\util\Collection.js:37:14)
    at Shard.wsEvent (D:\Discord_Bots\reportsystem\node_modules\eris\lib\gateway\Shard.js:888:61)
    at Shard.onPacket (D:\Discord_Bots\reportsystem\node_modules\eris\lib\gateway\Shard.js:400:26)
    at Shard._onWSMessage (D:\Discord_Bots\reportsystem\node_modules\eris\lib\gateway\Shard.js:2185:29)
    at WebSocket.emit (node:events:365:28)
    at WebSocket.emit (node:domain:470:12)
    at Receiver.receiverOnMessage (D:\Discord_Bots\reportsystem\node_modules\ws\lib\websocket.js:834:20)
    at Receiver.emit (node:events:365:28)
    at Receiver.emit (node:domain:470:12)
    at Receiver.dataMessage (D:\Discord_Bots\reportsystem\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (D:\Discord_Bots\reportsystem\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (D:\Discord_Bots\reportsystem\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (D:\Discord_Bots\reportsystem\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
```

I'm currently using `Eris 0.15.1` and `TypeScript v4.3.4` on `Windows 10 Pro x64`

**Comment by eritbh** [comment] 2021-06-29 20:05
This is probably worth asking about in the support server, https://discord.gg/eris. It may be a known issue with interactions (which Eris doesn't fully support yet). Maybe try listening to the `rawWS` event to figure out what sort of packet is being processed when this error occurs, to rule out Discord sending something unexpected in a non-Interactions packet?

Here's the line referenced in the traceback, in `Message#update`: https://github.com/abalabahaha/eris/blob/69f812c43cd8d9591d2ca455f7c8b672267a2ff6/lib/structures/Message.js#L249

Possibly related to/resolved by #1210 if it's an interactions-specific issue. Folks in the server can probably help you get set up to test against that branch if you want.

**Comment by bsian03** [comment] 2021-07-04 15:12
As mentioned, interaction responses are not yet supported with eris, but what data is being sent to Discord to receive this error? Endpoint/payload etc

**Comment by Awoocado** [comment] 2021-07-08 15:12
Can reproduce, only happens when editing an ephemeral message, doing so triggers MESSAGE_UPDATE event while having no mentions
No error message when editing a normal message
Endpoint: PATCH `/webhooks/<application_id>/<interaction_token>/messages/@original`
Payload:
```js
{
  t: 'MESSAGE_UPDATE',
  s: 33,
  op: 0,
  d: {
    id: '862706800372613141',
    flags: 64,
    embeds: [],
    content: 'This is not a ping pong table!',
    channel_id: '757435738701824091'
  }
}
```

**Comment by Awoocado** [comment] 2021-11-23 23:54
Apparently Discord now sends a bigger payload when editing an ephemeral message on both gateway v6 and v9 so this shouldn't be a problem now since it also sends an array for mentions.

Payload:
```js
{
  t: 'MESSAGE_UPDATE',
  s: 5,
  op: 0,
  d: {
    webhook_id: '911307550773874768',
    type: 0,
    tts: false,
    timestamp: '2021-11-23T23:45:17.979000+00:00',
    pinned: false,
    mentions: [],
    mention_roles: [],
    mention_everyone: false,
    interaction: [Object],
    id: '912851333982347325',
    flags: 64,
    embeds: [],
    edited_timestamp: '2021-11-23T23:45:18.961166+00:00',
    content: 'Boop',
    components: [],
    channel_id: '911307082060423191',
    author: [Object],
    attachments: [],
    application_id: '911307550773874768'
  }
}
```

**Comment by GoldenAngel2** [comment] 2021-11-24 00:21
After testing, this issue is fixed with the release of interactions.
> If you're still having this issue make sure you're updated to the latest version. 

And @Awoocado is correct this was caused by Discord not sending the normal data for ephemeral messages (that was changed months ago)

**Comment by DonovanDMC** [comment] 2022-06-07 19:17
As commented, this has been fixed on Discord's end

**Closed as completed by DonovanDMC** 2022-06-07 19:17 UTC
Labels: bug, Discord
